<?php
require_once 'PHPUnit/Framework.php';
require_once(dirname(__FILE__).'/../../config.php');

class ColumnFamilyTestObject extends PandraColumnFamily {
    public function init() {
        $this->setKeySpace('Keyspace1');
        $this->setName('Standard1');
    }
}

/**
 * Test class for PandraColumn.
 * Generated by PHPUnit on 2010-01-09 at 11:52:23.
 */
class PandraColumnTest extends PHPUnit_Framework_TestCase {

    public $obj = NULL;
    public $parentCF = NULL;

    public $columnName = 'mycolumn';

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * To test multiple nodes, add their connection strings here
     *
     * @access protected
     */
    protected function setUp() {
        $this->parentCF = new ColumnFamilyTestObject();
        $this->obj = new PandraColumn($this->columnName, $this->parentCF);
        PandraCore::connect('default', 'localhost');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {

    }

    public function testSetValue() {
        $this->obj->reset();
        $this->assertTrue($this->obj->setValue('NEW VALUE'));
        $this->assertTrue($this->obj->isModified());
    }

    public function testSetValueValidated() {
        $this->obj->reset();
        $this->obj->typeDef = array('string');
        $this->assertFalse($this->obj->setValue(1));


        $this->assertTrue(array_key_exists($this->columnName, $this->obj->getLastError()));
        $this->assertFalse($this->obj->isModified());
    }

    public function testBindTime() {
        $time = $this->obj->bindTime();
        $this->assertType(PHPUnit_Framework_Constraint_IsType::TYPE_INT, $time);
        $this->assertEquals($time, $this->obj->timestamp);

        $time = time();
        sleep(1);
        $colTime = $this->obj->bindTime($time);
        $this->assertType(PHPUnit_Framework_Constraint_IsType::TYPE_INT, $colTime);
        $this->assertEquals($time, $this->obj->timestamp);
    }

    public function testReset() {
        $this->assertFalse($this->obj->isModified());
        $this->obj->setValue('NEW VALUE');
        $this->assertTrue($this->obj->isModified());

        $this->obj->reset();
        $this->assertFalse($this->obj->isModified());
    }

    public function testCallbackValue() {
        $this->obj->callback = 'md5';
        $value = 'NEW VALUE';
        $this->obj->setValue($value);

        $this->assertEquals($this->obj->value, $value);

        $md5Value = md5($value);
        $this->assertEquals($this->obj->callbackValue(), $md5Value);


    }

    public function testCast() {

        $column = new cassandra_Column();
        $column->value = 'THRIFT COLUMN VALUE';

        $pandraColumn = $this->obj->cast($column, $this->parentCF);

        $this->assertEquals(get_class($pandraColumn), 'PandraColumn');
        $this->assertEquals($pandraColumn->value, $column->value);

        // @TODO cassandra_ColumnOrSupercolumn();

    }

    public function testIsModifed() {
        $this->assertFalse($this->obj->isModified());
        $this->obj->setValue('OH HI GREAT TO SEE YOU');
        $this->assertTrue($this->obj->isModified());
    }

    public function testSetParent() {
        $newCF = new ColumnFamilyTestObject();
        $this->obj->setParent($newCF);

        $this->assertEquals($newCF, $this->obj->getParent());
    }

    public function testGetParent() {
        $cf = $this->obj->getParent();
        $this->assertTrue($cf instanceof PandraColumnContainer);
    }

    public function testSaveLoadDelete() {
        $keyID = 'PandraColumnTest';
        $keySpace = 'Keyspace1';
        $columnFamily = 'Standard1';

        $value = 'test value';
        $this->obj->setValue($value);
        $this->assertTrue($this->obj->isModified());
        $this->assertTrue($this->obj->save($keyID, $keySpace, $columnFamily), $this->obj->getLastError());

        $column = array_pop(PandraCore::getCFSlice($keySpace, $keyID, $columnFamily))->column;
        $this->assertTrue($column->value == $value && $column->name = $this->obj->name && empty(PandraCore::$lastError), PandraCore::$lastError);

        $this->obj->delete();
        $this->assertTrue($this->obj->isModified() && $this->obj->isDeleted());
        $this->assertTrue($this->obj->save($keyID, $keySpace, $columnFamily), $this->obj->getLastError());

        $result = PandraCore::getCFSlice($keySpace, $keyID, $columnFamily);
        $this->assertTrue(empty($result) && empty(PandraCore::$lastError), PandraCore::$lastError);
    }

    public function testRegisterError() {
        $errorMsg = 'ERROR STRING';
        $this->obj->registerError($errorMsg);
        $this->assertTrue($this->obj->getLastError() == $errorMsg);

        $errors = $this->obj->getErrors();
        $this->assertTrue(array_pop($errors) == $errorMsg);

    }

}
?>